name: test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'
jobs:
  skip_duplicate:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_duplicate.outputs.should_skip }}
    steps:
      - id: skip_duplicate
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
  go-tests:
    needs: skip_duplicate
    if: needs.skip_duplicate.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.17.5'
          check-latest: true
      - name: Run Tests
        run: make tools pebble-start memcached-start test
        env:
          ACME_ENABLE_MEMCACHE_TEST: yes
